PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX jpost: <http://rdf.jpostdb.org/ontology/jpost.owl#>
PREFIX : <http://rdf.jpostdb.org/entry/>

SELECT DISTINCT ?pep_seq
WHERE {
  VALUES ?ds { {{datasets}} }
  ?ds jpost:hasPeptide/jpost:hasSequence/rdf:value ?pep_seq .
}
ORDER BY ?pep_seq